---
dist: trusty
language: ruby
cache: bundler
sudo: false
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
addons:
  apt:
    packages:
      - expect
script:
  bundle exec cucumber -f progress
matrix:
  include:
    - rvm: 2.1.9
      env: PUPPET_VERSION="~> 4.0"
    - rvm: 2.4.2
      env: PUPPET_VERSION="~> 5.0"
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
branches:
  only:
    - master
    - /^v\d/
before_install:
  - gem install bundler
